<link rel="stylesheet" href="../css/administrador.css">
<link rel="stylesheet" href="../css/cerrarsesion.css">
<link rel="stylesheet" href="../css/login.css">
<link rel="stylesheet" href="../css/menu.css">
<link rel="stylesheet" href="../css/recuperacionContraseña.css">
<link rel="stylesheet" href="../css/registrarAdministrador.css">
<link rel="stylesheet" href="../css/registrologin.css">
<link href="../css/bootstrap.min.css" rel="stylesheet"crossorigin="anonymous">
<link href="../css/all.min.css" rel="stylesheet"crossorigin="anonymous">
<script src="../js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>